# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        reduced:
            quality: 85
            filters:
                scale:
                    dim: [ 250, 250 ]
        shop_miniature:
            filters:

                # use and setup the "fixed" filter
                fixed:

                    # set the fixed size to "250x250" pixels
                    width: 250
                    height: 250
