twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        company_name: '%env(resolve:COMPANY_NAME)%'
        company_site: '%env(resolve:COMPANY_SITE)%'

